In [1]:
import pandas as pd

In [9]:
df=pd.read_csv('train_and_test2.csv')

In [11]:
df

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1305,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1306,1307,38.5,7.2500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1307,1308,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1308,1309,28.0,22.3583,0,1,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0

In [63]:
df.groupby("Sex")['Age'].agg(['mean','min','std','max','median'])

          mean   min        std   max  median
Sex
0    30.017888  0.33  12.659922  80.0    28.0
1    28.572082  0.17  13.300776  76.0    28.0

In [25]:
df.groupby("Sex")['Age'].describe()

     count       mean        std   min   25%   50%   75%   max
Sex
0    843.0  30.017888  12.659922  0.33  24.0  28.0  35.0  80.0
1    466.0  28.572082  13.300776  0.17  21.0  28.0  35.0  76.0

In [37]:
df.isnull().sum()

Passengerid    0
Age            0
Fare           0
Sex            0
sibsp          0
zero           0
zero.1         0
zero.2         0
zero.3         0
zero.4         0
zero.5         0
zero.6         0
Parch          0
zero.7         0
zero.8         0
zero.9         0
zero.10        0
zero.11        0
zero.12        0
zero.13        0
zero.14        0
Pclass         0
zero.15        0
zero.16        0
Embarked       2
zero.17        0
zero.18        0
2urvived       0
dtype: int64

In [39]:
df.groupby("Sex")['Age'].describe().sum()

count    1309.000000
mean       58.589970
std        25.960698
min         0.500000
25%        45.000000
50%        56.000000
75%        70.000000
max       156.000000
dtype: float64

In [71]:
# Create a list: all ages per each 'Sex' category
male_ages = df[df['Sex'] == 0]['Age'].dropna().tolist()
female_ages = df[df['Sex'] == 1]['Age'].dropna().tolist()

print("\nList of ages for Male:", male_ages[:5], "...")  # printing only first 5 values
print("List of ages for Female:", female_ages[:5], "...")

List of ages for Male: [22.0, 35.0, 28.0, 54.0, 2.0] ...
List of ages for Female: [38.0, 26.0, 35.0, 27.0, 14.0] ...

In [73]:
male_ages=df[df['Sex']==0]['Age'].dropna().tolist()
print(male_ages[:4])

[22.0, 35.0, 28.0, 54.0]

In [75]:
df1=pd.read_csv('IRIS.csv')

In [77]:
df1

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [79]:
df1.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [85]:
df1.describe().sum()

sepal_length    186.171399
sepal_width     168.987594
petal_length    174.473087
petal_width     157.961827
dtype: float64

In [92]:
df1["sepal_length"].describe()

count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000
Name: sepal_length, dtype: float64

In [94]:
df1.groupby("species").describe()

                sepal_length                                              \
                       count   mean       std  min    25%  50%  75%  max
species
Iris-setosa             50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
Iris-versicolor         50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
Iris-virginica          50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

                sepal_width         ... petal_length      petal_width         \
                      count   mean  ...          75%  max       count   mean
species                             ...
Iris-setosa            50.0  3.418  ...        1.575  1.9        50.0  0.244
Iris-versicolor        50.0  2.770  ...        4.600  5.1        50.0  1.326
Iris-virginica         50.0  2.974  ...        5.875  6.9        50.0  2.026


                      std  min  25%  50%  75%  max
species
Iris-setosa      0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]

In [96]:
df1.groupby("species").describe().sum()

sepal_length  count    150.000000
              mean      17.530000
              std        1.504540
              min       14.100000
              25%       16.625000
              50%       17.400000
              75%       18.400000
              max       20.700000
sepal_width   count    150.000000
              mean       9.162000
              std        1.017319
              min        6.500000
              25%        8.450000
              50%        9.200000
              75%        9.850000
              max       11.600000
petal_length  count    150.000000
              mean      11.276000
              std        1.195317
              min        8.500000
              25%       10.500000
              50%       11.400000
              75%       12.050000
              max       13.900000
petal_width   count    150.000000
              mean       3.596000
              std        0.579612
              min        2.500000
              25%        3.200000
              50%        3.500000
              75%        4.100000
              max        4.900000
dtype: float64